import React from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";
import Head from "next/head";
import Sidebar from "./Sidebar";
import RightBar from "./RightBar";
const Layout = ({ children, title, rightBar }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex py-2">
        <div className="basis-[20%] ">
          <Sidebar />
        </div>

        <div className="basis-[80%] overflow-y-scroll  bg-gray-100">
          <Navbar />
          <div className="flex flex-row">
            <div className={`${rightBar ? "basis-2/3" : "basis-3/3"}`}>
              {children}
            </div>
            <div
              className={`${
                rightBar ? "basis-1/3" : "basis-0"
              } mx-3 my-2 relative`}
            >
              {rightBar && <RightBar />}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Layout;
