import React from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";
import Head from "next/head";
import Sidebar from "./Sidebar";
import RightBar from "./RightBar";
const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex py-2">
        <div className="basis-[20%]  bg-red-600">
          <Sidebar />
        </div>

        <div className="basis-[55%] overflow-y-scroll  bg-gray-100">
          <Navbar />
          <div className="">{children}</div>
        </div>
        <div className="basis-[25%]  ">
          <RightBar />
        </div>
      </div>
    </>
  );
};

export default Layout;
